# Generated by Django 4.2 on 2023-06-03 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kach.exercisetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
